version: "3.5"

services:
  mongo:
    image: mongo:latest
    container_name: graylog-mongo
    volumes:
      - mongo-data:/data/db
    networks:
      custom_network:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: graylog-elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      custom_network:

  graylog:
    image: graylog/graylog:4.1
    container_name: graylog
    environment:
      - GRAYLOG_PASSWORD_SECRET=8QMv3Hz9xXy7fH28
      - GRAYLOG_ROOT_PASSWORD_SHA2=849089872588abe94cf072b76ebd4ba3a3d05533be606446c6f634fc875917c1
      # - GRAYLOG_HTTP_EXTERNAL_URI=http://seuDominioOuIP:9000/
    links:
      - mongo
      - elasticsearch
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"
      - "12201:12201"
      - "1514:1514"
      - "5555:5555"
    volumes:
      - graylog-data:/usr/share/graylog/data
    networks:
      custom_network:

  #for test
  php:
    image: diovanegabriel/php8.2-cli:latest
    container_name: graylog-php-test
    command: php -S 0.0.0.0:8080 -t /var/www/html
    links:
      - graylog
    depends_on:
      - graylog
    # ports:
    #   - "8080:8080"
    volumes:
      - ./:/var/www/html
    networks:
      - custom_network

networks:
  custom_network:
    external: true

volumes:
  mongo-data:
  elasticsearch-data:
  graylog-data: